### ISSUE TITLE
Program runs without result

### ISSUE THREAD

**Issue by HappyB1rthday** [lukasvst/dm-vio#12]
![QQ图片20220511220140](https://user-images.githubusercontent.com/52705056/167868516-dc2129f1-6b81-4ed3-9d8a-b15308835998.png)
Hi, The program is running, but there is no graphic or dot on Pangolin. The dataset is TUM-VI slides1. The resultsPrefix file exists but without anything. Is that normal? Or is there something wrong with the format of my input?
Thanks for your help.

**Comment by lukasvst** [comment]
No, this is not normal, you should see the images in the bottom left of the Pangolin window and the system should make it past the initialization phase.
The command looks ok at first glance.

Can you please post the full commandline output (especially the part before what's shown in the screenshot) so I can check if there is anything wrong with it?

**Comment by HappyB1rthday** [comment]
![J3K%O7YE{6MOP`Z)WCGDIUF](https://user-images.githubusercontent.com/52705056/167914373-fa763d1b-3141-4d33-a1d6-04f454f12025.png)
![KPM$X{(4B8@9I1K~0HT7D{E](https://user-images.githubusercontent.com/52705056/167914389-983230ac-de38-4ada-828b-447621d1d164.png)
Could you please check it for me

**Comment by lukasvst** [comment]
I don't see anything wrong in the output before it not initializing. I think there is something wrong with the installation, but it is a bit tricky to debug from a distance.
* Can you try to add the argument `useimu=0` and see if this changes something?
* Have you changed anything in the code? Maybe you could try the newest commit of the master branch.
* Another thing to try is to change line 66 in the file `src/dso/FullSystem/CoarseInitializer.cpp` to `printDebug=true;` 
This will enable more debug output. Could you paste the output when using this setting (maybe as a code block instead of a screenshot, as it will be quite long)?

**Comment by lukasvst** [comment]
One more thing: Could you try to set `mode=1` in the commandline arguments? As the images don't seem to arrive, the input to the photometric calibration could be wrong and this will disable it.

**Comment by lukasvst** [comment]
Do you have an update on this, were you able to resolve the issue? Otherwise I will close the issue in a week.

For future reference: My best guess is that the problem was that the images were somehow loaded as 8bit instead of 16bit. In this case a different pcalib file would need to be passed, otherwise the behavior is similar to what the @HappyB1rthday reported. For quickly testing this it is best to try to set `mode=1`as this mode does not use the pcalib file.

**Comment by GeJintian** [comment]
> Do you have an update on this, were you able to resolve the issue? Otherwise I will close the issue in a week.
> 
> For future reference: My best guess is that the problem was that the images were somehow loaded as 8bit instead of 16bit. In this case a different pcalib file would need to be passed, otherwise the behavior is similar to what the @HappyB1rthday reported. For quickly testing this it is best to try to set `mode=1`as this mode does not use the pcalib file.

I meet exactly the same problem, and setting mode=1 solves this problem. Thanks a lot.

**Comment by lukasvst** [comment]
Thanks for letting me know! 

One thing to note is that `mode=1` disables the photometric calibration which will slightly reduce the accuracy. (But it's great to try for debugging.)

So you could try using `mode=0` and passing `gamma=PATH_TO_DMVIO/configs/pcalib_linear_8bit.txt` which should hopefully work a bit better.

The explanation for this is that 8 bit images need a different pcalib (camera response calibration) file than 16 bit images, and in your case it seems like the images are loaded as 8bit.
